#dataset basics: 
dataset: ferrite
img_folder: images
label_folder: labels 
n_classes: 2 #how many classes are the images in the dataset divided into 

#train, validation and test split 
split_info:
  type: CSVSplit
  test_type: CSVSplit
  split_file: split_cv.csv 
  split_col_name: split
  val_split_num: 1 
  test_split_num: 0 
  train_reverse: True 
cross_validations: 
  val_splits: [1, 2, 3, 4, 5, 0] 
  test_splits: [0, 1, 2, 3, 4, 5] 

#data information 
#help standardizing the values and normalizing the image data before feeding it into the machine learning model 
train_size: [224, 224] #pixels that the images in the training model is resized to 
eval_size: [484, 645] #pixels that the images are evaluated images are resized to 
mean: [0.485, 0.456, 0.406] #mean values for RGB channels of the image dataset 
std: [0.229, 0.224, 0.225] #standard deviation values for RGB channels of the image dataset 

#data augmentation 
augmentations: 
  Flip: {p: 0.5} #there is a 50% chance that an image is flipped horizontally 
  ShiftScaleRotate: {shift_limit: 0, scale_limit: [0,1], rotate_limit: 45, p: 0.8} 
  RandomBrightnessContrast: {brightness_limit: 0.2, contrast_limit: 0.3, p: 0.8} 

#training
n_epochs: 11
train_repeat: 5 
loss_type: CE 
ignore_index: -1 #ignore index value for loss computation 
batch_size: 4 #determines training examples before making updates to its parameters 
optimizer: 
  type: AdamW
  encoder_lr: 5e-5 #encoder learning rate 
  decoder_lr: 5.e-4 #decoder learning rate 
  weight_decay: 1.e-2 
lr_scheduler: 
  type: MultiStepLR 
  params: {milestones: [100], gamma: 0.3}
metric: mIoU #mean intersection over union 
